### ISSUE TITLE
Tests don't show up on guest machine

### ISSUE THREAD

**Issue by zrno** [hbenl/vscode-test-explorer-liveshare#4]
Issue Type: <b>Bug</b>

The most simple example doesn't work. Live share on the same machine with 2 VSCode instances. Only 3 very simple and small tests visible in the "Test explorer" on the host instance. The guest instance doesn't show the tests. The "Reload tests" icon is circling all the time and never coming to an end.

Extension version: 1.0.5
VS Code version: Code 1.46.1 (cd9ea6488829f560dc949a8b2fb789f3cdc05f5d, 2020-06-17T21:13:20.174Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1240 v6 @ 3.70GHz (8 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (3.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by zrno** [comment]
Host instance logs:
![image](https://user-images.githubusercontent.com/13214299/86545104-66d25180-bf80-11ea-9d59-7e0998386204.png)

**Comment by matepek** [comment]
At server side I get:

```
[2020-07-11 05:19:42.839] [INFO] Passing on TestLoad event for Adapter #0: {"type":"started"}
[2020-07-11 05:19:43.473] [ERROR] Failed converting C:\Users\mate.pek\repo\vscode-catch2-test-adapter\test\cpp\doctest1.cpp to shared URI: Error: URI was not part of a workspace: file:///c%3A/Users/mate.pek/repo/vscode-catch2-test-adapter/test/cpp/doctest1.cpp
```
And a lot of similar errors.

**Comment by matepek** [comment]
Client side:
```
[2020-07-11 05:34:42.090] [DEBUG] Received TestLoad event for adapter #0: {"type":"started"}
[2020-07-11 05:34:42.090] [WARN] The TestLoad event was sent by an unknown adapter
```

This is a bit suspicious. 

My adapter sends the load finished events.

**Comment by matepek** [comment]
Here: https://github.com/hbenl/vscode-test-explorer-liveshare/blob/master/src/hostSession.ts#L85

```
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 's'
    |     property 'children' -> object with constructor 'Array'
    |     index 0 -> object with constructor 'o'
    --- property 'parent' closes the circle
	at JSON.stringify (<anonymous>)
	at /Volumes/Secure/repo/vscode-test-explorer-liveshare/out/hostSession.js:68:92
```

**Comment by matepek** [comment]
And here too: https://github.com/hbenl/vscode-test-explorer-liveshare/blob/master/src/hostSession.ts#L90

**Comment by matepek** [comment]
Damn, even if I fix it in this repo, the vsls uses JSON.stringify. :(

**Comment by matepek** [comment]
@zrno its working, right?

**Comment by darraghjones** [comment]
If this has been fixed, shouldn't you publish a new version of this extension to the Visual Studio Marketplace?

**Comment by hbenl** [comment]
@darraghjones This has been fixed in the Catch2 adapter extension, not this extension.
